-- X_VW_OS_SALEQUOTES_DAY
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (CONVERT(date, ORDERDATE, 101) = CONVERT(date, GETDATE(), 101)) AND (X_QUOTE_CREATED = 'Y')
-- X_VW_OS_SALEQUOTES_MTD
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (MONTH(ORDERDATE) = MONTH(GETDATE())) AND (YEAR(ORDERDATE) = YEAR(GETDATE())) AND (X_QUOTE_CREATED = 'Y')
-- X_VW_OS_SALEQUOTES_LAST_MNT
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (X_QUOTE_CREATED = 'Y') AND (ORDERDATE <= DATEADD(ms, - 2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0))) AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(m, 
                      DATEDIFF(m, 0, GETDATE()) - 1, 0), 102))
-- X_VW_OS_SALEQUOTES_LAST3_MNT
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (X_QUOTE_CREATED = 'Y') AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0), 102)) AND (ORDERDATE <= DATEADD(MONTH, 
                      DATEDIFF(MONTH, - 1, GETDATE()) - 1, - 1))                      
-- X_VW_OS_SALEORDERS_DAY
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND (CONVERT(date, ORDERDATE, 101) = CONVERT(date, GETDATE(), 101))
-- X_VW_OS_SALEORDERS_MTD
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND (MONTH(ORDERDATE) = MONTH(GETDATE())) AND (YEAR(ORDERDATE) = YEAR(GETDATE()))
-- X_VW_OS_SALEORDERS_LAST_MNT
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND  (ORDERDATE <= DATEADD(ms, - 2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0))) AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(m, DATEDIFF(m, 0, GETDATE()) - 1, 0), 102)) 
-- X_VW_OS_SALEORDERS_LAST3_MNT
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND  (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0), 102)) AND (ORDERDATE <= DATEADD(MONTH, DATEDIFF(MONTH, - 1, GETDATE()) - 1, - 1))  
-- X_VW_OS_SALEINVOICES_DAY
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (CONVERT(date, dbo.DR_TRANS.TRANSDATE, 101) = CONVERT(date, GETDATE(), 101)) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_MTD
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE = 0) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_LAST_MNT
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE = 1) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_LAST3_MNT
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE IN (3, 2, 1)) AND (dbo.DR_TRANS.TRANSTYPE = 1)