-- X_VW_OS_SALEQUOTES_BYDATE
SELECT     SOH.ORDERDATE, COUNT(SOH.SEQNO) AS QUOTEQTY, ISNULL(SUM(SOH.SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(SOH.X_GP), 0) AS QUOTEPROFIT, 
                      ISNULL(SUM(TRG.MTD_QUOTE_VAL / TRG.NO_OF_WORKING_DAYS), 0) AS QUOTEVALUETARGET, ISNULL(SUM(TRG.MTD_QUOTE_QTY / TRG.NO_OF_WORKING_DAYS), 0) AS QUOTEQTYTARGET, 
                      ISNULL(SUM(TRG.MTD_QUOTE_PROFIT / TRG.NO_OF_WORKING_DAYS), 0) AS QUOTEPROFITTARGET
FROM         dbo.SALESORD_HDR AS SOH INNER JOIN
                      dbo.X_Targets AS TRG ON YEAR(SOH.ORDERDATE) = TRG.YEAR AND (MONTH(DATEADD(m, 6, SOH.ORDERDATE)) = TRG.PERIOD_NO OR
                      MONTH(DATEADD(m, - 6, SOH.ORDERDATE)) = TRG.PERIOD_NO)
WHERE     (SOH.X_QUOTE_CREATED = 'Y') OR
                      (SOH.STATUS = 3)
GROUP BY SOH.ORDERDATE
-- X_VW_OS_SALEQUOTES_DAY
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (CONVERT(date, ORDERDATE, 101) = CONVERT(date, GETDATE(), 101)) AND (X_QUOTE_CREATED = 'Y')
-- X_VW_OS_SALEQUOTES_MTD
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (MONTH(ORDERDATE) = MONTH(GETDATE())) AND (YEAR(ORDERDATE) = YEAR(GETDATE())) AND (X_QUOTE_CREATED = 'Y')
-- X_VW_OS_SALEQUOTES_LAST_MNT
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (X_QUOTE_CREATED = 'Y') AND (ORDERDATE <= DATEADD(ms, - 2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0))) AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(m, 
                      DATEDIFF(m, 0, GETDATE()) - 1, 0), 102))
-- X_VW_OS_SALEQUOTES_LAST3_MNT
SELECT     COUNT(SEQNO) AS QUOTEQTY, ISNULL(SUM(SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(X_GP), 0) AS QUOTEPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (X_QUOTE_CREATED = 'Y') AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0), 102)) AND (ORDERDATE <= DATEADD(MONTH, 
                      DATEDIFF(MONTH, - 1, GETDATE()) - 1, - 1))   
-- X_VW_OS_SALEORDERS_BYDATE
SELECT     SOH.ORDERDATE, COUNT(SOH.SEQNO) AS ORDERQTY, ISNULL(SUM(SOH.SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(SOH.X_GP), 0) AS ORDERPROFIT, 
                      ISNULL(SUM(TRG.MTD_ORDER_VAL / TRG.NO_OF_WORKING_DAYS), 0) AS ORDERVALUETARGET, ISNULL(SUM(TRG.MTD_ORDER_QTY / TRG.NO_OF_WORKING_DAYS), 0) 
                      AS ORDERQTYTARGET, ISNULL(SUM(TRG.MTD_ORDER_PROFIT / TRG.NO_OF_WORKING_DAYS), 0) AS ORDERPROFITTARGET
FROM         dbo.SALESORD_HDR AS SOH INNER JOIN
                      dbo.X_Targets AS TRG ON MONTH(SOH.ORDERDATE) = TRG.PERIOD_NO AND YEAR(SOH.ORDERDATE) = TRG.YEAR
WHERE     (SOH.STATUS <= 2)
GROUP BY SOH.ORDERDATE


-- X_VW_OS_SALEORDERS_DAY
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND (CONVERT(date, ORDERDATE, 101) = CONVERT(date, GETDATE(), 101))
-- X_VW_OS_SALEORDERS_MTD
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND (MONTH(ORDERDATE) = MONTH(GETDATE())) AND (YEAR(ORDERDATE) = YEAR(GETDATE()))
-- X_VW_OS_SALEORDERS_LAST_MNT
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND  (ORDERDATE <= DATEADD(ms, - 2, DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0))) AND (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(m, DATEDIFF(m, 0, GETDATE()) - 1, 0), 102)) 
-- X_VW_OS_SALEORDERS_LAST3_MNT
SELECT     COUNT(SEQNO) AS ORDERQTY, ISNULL(SUM(SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(X_GP), 0) AS ORDERPROFIT
FROM         dbo.SALESORD_HDR AS SOH
WHERE     (STATUS < 2) AND  (CONVERT(date, ORDERDATE, 102) >= CONVERT(date, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 3, 0), 102)) AND (ORDERDATE <= DATEADD(MONTH, DATEDIFF(MONTH, - 1, GETDATE()) - 1, - 1))  
-- -- X_VW_OS_SALEINVOICES_BYDATE
SELECT     TRN.TRANSDATE, COUNT(TRN.SEQNO) AS INVOICEQTY, ISNULL(SUM(TRN.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(SOH.X_GP), 0) AS INVOICEPROFIT, 
                      ISNULL(SUM(TRG.MTD_INV_VAL / TRG.NO_OF_WORKING_DAYS), 0) AS INVOICEVALUETARGET, ISNULL(SUM(TRG.MTD_INV_QTY / TRG.NO_OF_WORKING_DAYS), 0) AS INVOICEQTYTARGET, 
                      ISNULL(SUM(TRG.MTD_INV_PROFIT / TRG.NO_OF_WORKING_DAYS), 0) AS INVOICEPROFITTARGET
FROM         dbo.DR_TRANS AS TRN INNER JOIN
                      dbo.SALESORD_HDR AS SOH ON SOH.SEQNO = TRN.SO_SEQNO INNER JOIN
                      dbo.X_Targets AS TRG ON MONTH(SOH.ORDERDATE) = TRG.PERIOD_NO AND YEAR(SOH.ORDERDATE) = TRG.YEAR
WHERE     (TRN.TRANSTYPE = 1)
GROUP BY TRN.TRANSDATE
-- X_VW_OS_SALEINVOICES_DAY
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (CONVERT(date, dbo.DR_TRANS.TRANSDATE, 101) = CONVERT(date, GETDATE(), 101)) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_MTD
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE = 0) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_LAST_MNT
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE = 1) AND (dbo.DR_TRANS.TRANSTYPE = 1)
-- X_VW_OS_SALEINVOICES_LAST3_MNT
SELECT     COUNT(dbo.DR_TRANS.SEQNO) AS INVOICEQTY, ISNULL(SUM(dbo.DR_TRANS.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(dbo.SALESORD_HDR.X_GP), 0) AS INVOICEPROFIT
FROM         dbo.DR_TRANS INNER JOIN
                      dbo.SALESORD_HDR ON dbo.SALESORD_HDR.SEQNO = dbo.DR_TRANS.SO_SEQNO
WHERE     (dbo.DR_TRANS.AGE IN (3, 2, 1)) AND (dbo.DR_TRANS.TRANSTYPE = 1)

-- X_VW_OS_SALEQUOTES_BYPERIOD
SELECT     TRG.YEAR,TRG.PERIOD_NO, COUNT(SOH.SEQNO) AS QUOTEQTY, ISNULL(SUM(SOH.SUBTOTAL), 0) AS QUOTETOTAL, ISNULL(SUM(SOH.X_GP), 0) AS QUOTEPROFIT, ISNULL(SUM(TRG.MTD_QUOTE_VAL), 0) 
                      AS QUOTEVALUETARGET, ISNULL(SUM(TRG.MTD_QUOTE_QTY), 0) AS QUOTEQTYTARGET, ISNULL(SUM(TRG.MTD_QUOTE_PROFIT), 0) AS QUOTEPROFITTARGET, 
                      ISNULL(SUM(TRG.NO_OF_WORKING_DAYS), 0) AS NOOFWORKINGDAYS
FROM         dbo.X_Targets AS TRG LEFT JOIN
                      dbo.SALESORD_HDR AS SOH ON YEAR(SOH.ORDERDATE) = TRG.YEAR AND ((MONTH(DATEADD(m, 6, SOH.ORDERDATE)) = TRG.PERIOD_NO OR
                      MONTH(DATEADD(m, - 6, SOH.ORDERDATE)) = TRG.PERIOD_NO)) AND ((SOH.X_QUOTE_CREATED = 'Y') OR (SOH.STATUS = 3))
GROUP BY TRG.YEAR,TRG.PERIOD_NO order by TRG.YEAR,TRG.PERIOD_NO

-- X_VW_OS_SALEORDERS_BYPERIOD  
  SELECT     TRG.YEAR,TRG.PERIOD_NO, COUNT(SOH.SEQNO) AS ORDERQTY, ISNULL(SUM(SOH.SUBTOTAL), 0) AS ORDERTOTAL, ISNULL(SUM(SOH.X_GP), 0) AS ORDERPROFIT, ISNULL(SUM(TRG.MTD_ORDER_VAL), 
                      0) AS ORDERVALUETARGET, ISNULL(SUM(TRG.MTD_ORDER_QTY), 0) AS ORDERQTYTARGET, ISNULL(SUM(TRG.MTD_ORDER_PROFIT), 0) AS ORDERPROFITTARGET, 
                      ISNULL(SUM(TRG.NO_OF_WORKING_DAYS), 0) AS NOOFWORKINGDAYS
FROM         dbo.X_Targets AS TRG LEFT JOIN
                       dbo.SALESORD_HDR AS SOH ON YEAR(SOH.ORDERDATE) = TRG.YEAR AND (MONTH(DATEADD(m, 6, SOH.ORDERDATE)) = TRG.PERIOD_NO OR
                      MONTH(DATEADD(m, - 6, SOH.ORDERDATE)) = TRG.PERIOD_NO) AND (SOH.STATUS <= 2)
GROUP BY TRG.YEAR,TRG.PERIOD_NO order by TRG.YEAR,TRG.PERIOD_NO
-- X_VW_OS_SALEINVOICES_BYPERIOD
SELECT     TRG.YEAR,TRG.PERIOD_NO, COUNT(SOHTRN.SEQNO) AS INVOICEQTY, ISNULL(SUM(SOHTRN.SUBTOTAL), 0) AS INVOICETOTAL, ISNULL(SUM(SOHTRN.X_GP), 0) AS INVOICEPROFIT, ISNULL(SUM(TRG.MTD_INV_VAL), 0) 
                      AS INVOICEVALUETARGET, ISNULL(SUM(TRG.MTD_INV_QTY), 0) AS INVOICEQTYTARGET, ISNULL(SUM(TRG.MTD_INV_PROFIT), 0) AS INVOICEPROFITTARGET, 
                      ISNULL(SUM(TRG.NO_OF_WORKING_DAYS), 0) AS NOOFWORKINGDAYS
FROM       dbo.X_Targets AS TRG LEFT JOIN
                      (SELECT TRN.TRANSDATE,TRN.SEQNO,TRN.SUBTOTAL,SOH.X_GP from dbo.SALESORD_HDR AS SOH,dbo.DR_TRANS AS TRN where SOH.SEQNO = TRN.SO_SEQNO AND (TRN.TRANSTYPE = 1)) AS SOHTRN ON YEAR(SOHTRN.TRANSDATE) = TRG.YEAR AND (MONTH(DATEADD(m, 6, SOHTRN.TRANSDATE)) = TRG.PERIOD_NO OR
                      MONTH(DATEADD(m, - 6, SOHTRN.TRANSDATE)) = TRG.PERIOD_NO) 

GROUP BY TRG.YEAR,TRG.PERIOD_NO order by TRG.YEAR,TRG.PERIOD_NO