----------- SQLServer-------
-- DROP TABLE USER_ROLE
-- DROP TABLE ROLE
-- DROP TABLE ONESYS_USER
-- CREATE TABLE ONESYS_USER(USER_ID INT NOT NULL IDENTITY(1,1),USER_NAME VARCHAR(44) NOT NULL,PASSWORD VARCHAR(524) NOT NULL,EMAIL VARCHAR(44),FIRST_NAME VARCHAR(44) NOT NULL,LAST_NAME VARCHAR(44),ACTIVE SMALLINT NOT NULL,PRIMARY KEY (USER_ID));
-- CREATE TABLE ROLE(ROLE_ID INT NOT NULL IDENTITY(1,1),ROLE VARCHAR(44) NOT NULL,PRIMARY KEY (ROLE_ID));
-- CREATE TABLE USER_ROLE(USER_ID INT NOT NULL,ROLE_ID INT NOT NULL,FOREIGN KEY (USER_ID) REFERENCES ONESYS_USER (USER_ID),FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID));

-- INSERT INTO ROLE (ROLE) VALUES('ADMIN')
-- SELECT * FROM ROLE

------  MySql -----------------
-- CREATE TABLE ONESYS_USER(USER_ID INT NOT NULL AUTO_INCREMENT,USER_NAME VARCHAR(44) NOT NULL,PASSWORD VARCHAR(524) NOT NULL,EMAIL VARCHAR(44),FIRST_NAME VARCHAR(44) NOT NULL,LAST_NAME VARCHAR(44),ACTIVE SMALLINT NOT NULL,PRIMARY KEY (USER_ID));
-- CREATE TABLE ROLE(ROLE_ID INT NOT NULL AUTO_INCREMENT,ROLE VARCHAR(44) NOT NULL,PRIMARY KEY (ROLE_ID));
-- CREATE TABLE USER_ROLE(USER_ID INT NOT NULL,ROLE_ID INT NOT NULL,FOREIGN KEY (USER_ID) REFERENCES ONESYS_USER (USER_ID),FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID));
